services:
  - type: worker
    name: telegram-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
